name: whilabel
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0-260.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1

  # 불변객체 만들때 사용하는 패키지
  json_serializable: ^6.7.0
  json_annotation: ^4.8.1
  freezed_annotation: ^2.2.0
  build: ^2.0.1
  collection: ^1.15.0
  graphs: ">=2.0.0 <2.3.0"

  # 간편로그인 패키지
  kakao_flutter_sdk: ^1.5.0
  kakao_flutter_sdk_user: ^1.5.0
  google_sign_in: ^6.1.5

  # firebase 패키지
  firebase_core: ^2.15.1
  cloud_firestore_odm: ^1.0.0-dev.58
  cloud_firestore: ^4.7.0
  firebase_auth: ^4.6.3
  flutter_svg: ^2.0.7
  firebase_storage: ^11.2.7

  # hive 패키지
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_dotenv: ^5.1.0

  # UI & 디자인 패키지
  flutter_spinkit: ^5.2.0
  flutter_easyloading: ^3.0.5
  readmore: ^2.1.0
  searchfield: ^0.8.4
  flutter_native_splash: ^2.3.2 # splash pack
  popup_banner: ^1.0.0

  # image 관련 패키지
  photo_gallery: ^2.1.1
  transparent_image: ^2.0.1
  flutter_native_image: ^0.0.6+1

  # 기타 패키지
  dartx: ^1.2.0
  provider: ^6.0.5
  get: ^4.6.5
  http: ^1.1.0

  uuid: ^4.0.0
  intl: ^0.18.1
  emailjs: ^1.3.0
  mobile_scanner: ^3.4.1
  simple_barcode_scanner: ^0.0.8
  firebase_database: ^10.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  # 불변객체 만들때 사용하는 패키지
  build_runner: 2.4.3
  freezed: ^2.3.5

  # firebase 패키지
  cloud_firestore_odm_generator: ^1.0.0-dev.58

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo/
    - assets/login/
    - assets/icon/
    - assets/screen_image/
    - assets/icon/_back/
    - assets/icon/_taste/
    - assets/icon/_check/
    - assets/icon/on_boarding/
    - assets/icon/pop_menu/
    - assets/config/.env
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/pretendard/Pretendard-Thin.ttf
          weight: 100
        - asset: assets/fonts/pretendard/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/pretendard/Pretendard-Light.ttf
          weight: 300
        - asset: assets/fonts/pretendard/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/pretendard/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/pretendard/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/pretendard/Pretendard-Bold.ttf
          weight: 700
        - asset: assets/fonts/pretendard/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/pretendard/Pretendard-Black.ttf
          weight: 900
